class Language  {
  static const Map<String, dynamic> english = {
    'name_app': '1 Weateher',
    // Text của duy
    // bottom navigation
    'today': 'TODAY',
    'forecast': 'FORECAST',
    'radar': 'RADAR',
    // text ở today screen
    'hourly_forecast': 'Hourly Forecast',
    'current_details': 'Current Details',
    'prep': 'Precipitation',
    'wind': 'Wind',
    'humi': 'Humidity',
    'visi': 'Visibility',
    'dew': 'Dew point',
    'press': 'Pressure',
    'daily_forecast': 'Daily Forecast',
    'air_quality': 'Air Quality',
    'allergy_outlook': 'Allergy Outlook',
    'grass': 'Grass pollen',
    'weed': 'Weed pollen',
    'tree': 'Tree pollen',
    'sun_moon': 'Sun & Moon',
    //text forecast screen
    'today1': 'TODAY',
    //text button
    'bt_see_more': 'See More Details',
    // Text của đạo
    'language': 'Language',
    'language_unit': 'Language and Unit',
    // Text của chiến
    'Saved Locations': 'Saved Location',
    'SAVED LOCATIONS' : 'SAVED LOCATIONS',
    'Click, hold and move the lever to change the position of your locations.': 'Click, hold and move the lever to change the position of your locations.',
    'Current location': 'Current location',
    'Click to get location': 'Click to get location',
    'Tap on the edit icon to add a label. For e.g., Home, Office...' : 'Tap on the edit icon to add a label. For e.g., Home, Office...',
    'Manage': 'Manage',
    'Search location': 'Search location',
    'Long' : 'Long',
    'Lat': 'Lat',
    "This will remove": "This will remove",
    "from your list of saved locations.": "from your list of saved locations.",
    "Are you sure?": "Are you sure?",
    "Yes": "Yes",
    "No": "No",
    "Item removed successfully": "Item removed successfully",
    "Item not found in history": "Item not found in history",
    "The app does not have access to your location.": "The app does not have access to your location.",
    "Currently": "Currently",
    "Manage Locations": " Manage Locations",
    "Agree": "Agree",
    "Cancel": "Cancel",
    'Location access': 'Location access',
    "Add a label": "Add a label",
    "e.g. Home": "e.g. Home",
    "Home": "Home",
    "School": "School",
    "Hospital": "Hospital",
    "Work": "Work",
    "Gym": "Gym",
    "Park": "Park",
    "Bus": "Bus",
    "Favorite": "Favorite",
    "Other": "Other",
    "SAVE CHANGES": "SAVE CHANGES",
    "The app needs access to your location to provide relevant information. Do you want to allow it?": "The app needs access to your location to provide relevant information. Do you want to allow it?",

  };
  static const Map<String, dynamic> vietnam = {
    'name_app': '1 Weather',
    // Text của duy
    // bottom navigation
    'today': 'Hiện tại',
    'forecast': 'Dự báo',
    'radar': 'RADAR',
    // text ở today screen
    'hourly_forecast': 'Theo giờ',
    'current_details': 'Hiện tại',
    'prep': 'Lượng mưa',
    'wind': 'Gió',
    'humi': 'Độ ẩm',
    'visi': 'Tầm nhìn',
    'dew': 'Điểm sương',
    'press': 'Áp suất',
    'daily_forecast': 'Theo Ngày',
    'air_quality': 'Chất lượng không khí',
    'allergy_outlook': 'Dự báo mức độ dị ứng',
    'grass': 'phấn hoa cỏ',
    'weed': 'phấn hoa cỏ dại',
    'tree': 'phấn từ cây',
    'sun_moon': 'Sun & Moon',
    //text cua forecast screen
    // text của thứ trong ngày
    'today1': 'Hôm nay',
    // Text của đạo
    'language': 'Ngôn ngữ',
    'language_unit': 'Ngôn ngữ và đơn vị',
    // Text của chiến
    'SAVED LOCATIONS': 'VỊ TRÍ ĐÃ LƯU',
    'Click, hold and move the lever to change the position of your locations.': 'Nhấn, giữ và di chuyển để thay đổi vị trí của các địa điểm của bạn.',
    'Tap on the edit icon to add a label. For e.g., Home, Office...': 'Nhấn vào biểu tượng chỉnh sửa để thêm nhãn. Ví dụ: Nhà, Văn phòng...',
    'Current location': 'Vị trí hiện tại',
    'Click to get location': 'Nhấn để lấy vị trí',
    'Saved Locations': 'Vị trí đã lưu',
    'Manage': 'Quản lý',
    'Search location': 'Tìm kiếm vị trí bất kì',
    'Long' : 'Kinh độ',
    'Lat': 'Vĩ độ',
    "This will remove": "Vị trí",
    "from your list of saved locations.": "sẽ xóa khỏi danh sách các vị trí đã lưu của bạn.",
    "Are you sure?": "Bạn có chắc không?",
    "Yes": "Có",
    "No": "Không",
    "Item removed successfully": "Xóa thành công",
    "Item not found in history": "Không tìm thấy trong lịch sử",
    "The app does not have access to your location.": "Ứng dụng không có quyền truy cập vị trí của bạn.",
    "Currently": "Hiện tại",
    "Manage Locations": "Quản lý vị trí",
    "Agree": "Đồng ý",
    "Cancel": "Hủy",
    'Location access': 'Quyền truy cập vị trí',
    "Add a label": "Thêm nhãn",
    "e.g. Home": "ví dụ: Nhà",
    "School": "Trường",
    "Hospital": "Bệnh viện",
    "Work": "Công ty",
    "Gym": "Gym",
    "Park": "Công viên",
    "Home": "Nhà",
    "Bus": "Xe buýt",
    "Favorite": "Yêu thích",
    "Other": "Khác",
    "SAVE CHANGES": "Lưu thay đổi",
    "The app needs access to your location to provide relevant information. Do you want to allow it?": "Ứng dụng cần truy cập vị trí của bạn để cung cấp thông tin phù hợp. Bạn có muốn cho phép?"
  };
}