class Language  {
  static const Map<String, dynamic> english = {
    'name_app': '1 Weateher',
    // Text của duy
    // bottom navigation
    'today': 'TODAY',
    'forecast': 'FORECAST',
    'radar': 'RADAR',
    // text ở today screen
    'hourly_forecast': 'Hourly Forecast',
    'current_details': 'Current Details',
    'prep': 'Precipitation',
    'wind': 'Wind',
    'humi': 'Humidity',
    'visi': 'Visibility',
    'dew': 'Dew point',
    'press': 'Pressure',
    'daily_forecast': 'Daily Forecast',
    'air_quality': 'Air Quality',
    'allergy_outlook': 'Allergy Outlook',
    'grass': 'Grass pollen',
    'weed': 'Weed pollen',
    'tree': 'Tree pollen',
    'sun_moon': 'Sun & Moon',
    //text forecast screen
    'today1': 'TODAY',
    //text button
    'bt_see_more': 'See More Details',
    // Text của đạo
    'language': 'Language',
    'language_unit': 'Language and Unit',
    'Settings': 'Settings',
    'Manage Locations': 'Manage Locations',
    'Add Widgets': 'Add Widgets',
    'Daily Summary Notification': 'Daily Summary Notification',
    'More Settings': 'More Settings',
    'SAVED LOCATIONS': 'SAVED LOCATIONS',
    'Use Current Location': 'Use Current Location',
    'Get a daily': 'Get a daily brief of your day at a time of your choosing',
    'Select time': 'Select time',
    'Cancel': 'Cancel',
    'OK': 'OK',
    'Alerts': 'Cảnh Báo',
    'App Theme': 'Màu Nền',
    'Auto-Refresh': 'Tự động làm mới',
    'minutes': 'minutes',
    'Additional Settings': 'Cài Đặt Thêm',
    'Select your': 'Select your interval to automatically refresh notifications',
    'Get hyperlocal': 'Get hyperlocal weather updates for your pinpoint location',
    'Sticky Notifications': 'Sticky Notifications',
    'Weather alerts': 'Weather alerts from the National Weather Service',
    'Types of Content': 'Types of Content',
    'Weather Highlights': 'Weather Highlights',
    'Get forecasts': 'Get forecasts and alerts in your area',
    'NWS Alerts': 'NWS Alerts',
    'Get weather alerts': 'Get weather alerts from the National Weather Service',
    'Weather News': 'Weather News',
    'Get weather news & videos': 'Get weather news & videos',
    'Location': 'Location',
    'Current Location': 'Current Location',
    'Select Language': 'Select Language',
    'Units': 'Units',
    'Customize': 'Customize',
    'Off': 'Off',
    'Customize Units': 'Customize Units',
    'Temperature': 'Temperature',
    'Wind Units': 'Wind Units',
    'Distance': 'Distance',
    'Select wind': 'Select your preferred win speed unit',
    'Select distance': 'Select your preferred distance unit',
    'Pressure Units': 'Pressure Units',
    'Select pressure': 'Select your preferred pressure unit',
    'Current Selection': 'Current Selection',
    'Select Pressure Unit': 'Select Pressure Unit',
    'Select Theme': 'Select Theme',
    'Light': 'Light',
    'Dark': 'Dark',
    // Text của chiến
  };
  static const Map<String, dynamic> vietnam = {
    'name_app': '1 Weather',
    // Text của duy
    // bottom navigation
    'today': 'Hiện tại',
    'forecast': 'Dự báo',
    'radar': 'RADAR',
    // text ở today screen
    'hourly_forecast': 'Theo giờ',
    'current_details': 'Hiện tại',
    'prep': 'Lượng mưa',
    'wind': 'Gió',
    'humi': 'Độ ẩm',
    'visi': 'Tầm nhìn',
    'dew': 'Điểm sương',
    'press': 'Áp suất',
    'daily_forecast': 'Theo Ngày',
    'air_quality': 'Chất lượng không khí',
    'allergy_outlook': 'Dự báo mức độ dị ứng',
    'grass': 'phấn hoa cỏ',
    'weed': 'phấn hoa cỏ dại',
    'tree': 'phấn từ cây',
    'sun_moon': 'Sun & Moon',
    //text cua forecast screen
    // text của thứ trong ngày
    'today1': 'Hôm nay',
    // Text của đạo
    'language': 'Ngôn Ngữ',
    'language_unit': 'Ngôn Ngữ Và Đơn Vị',
    'Settings': 'Cài Đặt',
    'Manage Locations': 'Quản lý Vị Trí',
    'Add Widgets': 'Thêm Tiện Ích',
    'Daily Summary Notification': 'Thông Báo Tóm Tắt Hàng Ngày',
    'More Settings': 'Cài Đặt Khác',
    'SAVED LOCATIONS': 'Vị Trí Đã Lưu',
    'Use Current Location': 'Sử Dụng Vị Trí Hiện Tại',
    'Get a daily': 'Nhận bản tóm tắt hàng ngày về ngày của bạn vào thời điểm bạn chọn',
    'Select time': 'Cài đặt giờ',
    'Cancel': 'Hủy bỏ',
    'OK': 'Chọn',
    'Alerts': 'Cảnh Báo',
    'App Theme': 'Màu Nền',
    'Auto-Refresh': 'Tự động làm mới',
    'minutes': 'phút',
    'Additional Settings': 'Cài Đặt Thêm',
    'Select your': 'Chọn khoảng thời gian của bạn để tự động làm mới thông báo',
    'Get hyperlocal': 'Nhận thông tin cập nhật về thời tiết địa phương cho vị trí chính xác của bạn',
    'Sticky Notifications': 'Thông báo cố định',
    'Weather alerts': 'Cảnh báo thời tiết từ Cơ quan Dịch vụ Thời tiết Quốc gia',
    'Types of Content': 'Các loại nội dung',
    'Weather Highlights': 'Điểm nổi bật thời tiết',
    'Get forecasts': 'Nhận dự báo và cảnh báo trong khu vực của bạn',
    'NWS Alerts': 'Cảnh báo từ NWS',
    'Get weather alerts': 'Nhận cảnh báo thời tiết từ Cơ quan Dịch vụ Thời tiết Quốc gia',
    'Weather News': 'Tin tức thời tiết',
    'Get weather news & videos': 'Nhận tin tức và video về thời tiết',
    'Location': 'Vị trí',
    'Current Location': 'Vị trí hiện tại',
    'Select Language': 'Chọn ngôn ngữ',
    'Units': 'Đơn vị',
    'Customize': 'Tùy chỉnh',
    'Off': 'Tắt',
    'Customize Units': 'Tùy chỉnh đơn vị',
    'Temperature': 'Nhiệt độ',
    'Wind Units': 'Đơn vị gió',
    'Distance': 'Khoảng cách',
    'Select wind': 'Chọn đơn vị tốc độ gió ưa thích',
    'Select distance': 'Chọn đơn vị khoảng cách ưa thích',
    'Pressure Units': 'Đơn vị áp suất',
    'Select pressure': 'Chọn đơn vị áp suất ưa thích',
    'Current Selection': 'Lựa chọn hiện tại',
    'Select Pressure Unit': 'Chọn đơn vị áp suất',
    'Select Theme': 'Chọn chủ đề',
    'Light': 'Sáng',
    'Dark': 'Tối',

    // Text của chiến
  };
}