class Language  {
  static const Map<String, dynamic> english = {
    'name_app': '1 Weateher',
    // Text của duy
    // bottom navigation
    'today': 'TODAY',
    'forecast': 'FORECAST',
    'radar': 'RADAR',
    // text ở today screen
    'hourly_forecast': 'Hourly Forecast',
    'current_details': 'Current Details',
    'prep': 'Precipitation',
    'wind': 'Wind',
    'humi': 'Humidity',
    'visi': 'Visibility',
    'dew': 'Dew point',
    'press': 'Pressure',
    'daily_forecast': 'Daily Forecast',
    'air_quality': 'Air Quality',
    'allergy_outlook': 'Allergy Outlook',
    'grass': 'Grass pollen',
    'weed': 'Weed pollen',
    'tree': 'Tree pollen',
    'sun_moon': 'Sun & Moon',
    //text cua forecast screen
    // text của thứ trong ngày
    // text forecast screen
    'hourly': 'Hourly',
    'daily': 'Daily',

    //text trong air_quality_table
    'advice': 'Air quality between 51 and 100 is not ideal, so keep an eye on it',
    // Text  trong current_detail_table
    'feel_like': ' Feel like ',
    // text của weather
    'Thunderstorm with light rain' : 'Thunderstorm with light rain',
    'Thunderstorm with rain' : 'Thunderstorm with rain',
    'Thunderstorm with heavy rain' : 'Thunderstorm with heavy rain',
    'Thunderstorm with light drizzle' : 'Thunderstorm with light drizzle',
    'Thunderstorm with drizzle' : 'Thunderstorm with drizzle',
    'Thunderstorm with heavy drizzle' : 'Thunderstorm with heavy drizzle',
    'Thunderstorm with Hail' : 'Thunderstorm with Hail',

    'Light drizzle' : 'Light drizzle',
    'Drizzle' : 'Drizzle',
    'Heavy drizzle' : 'Heavy drizzle',

    'Light rain' : 'Light rain',
    'Moderate rain' : 'Moderate rain',
    'Heavy rain' : 'Heavy rain',
    'Freezing rain' : 'Freezing rain',
    'Light shower rain' : 'Light shower rain',
    'Shower rain' : 'Shower rain',
    'Heavy shower rain' : 'Heavy shower rain',

    'Light snow' : 'Light snow',
    'Snow' : 'Snow',
    'Heavy snow' : 'Heavy snow',
    'Mix snow/rain' : 'Mix snow/rain',
    'Sleet' : 'Sleet',
    'Heavy sleet' : 'Heavy sleet',
    'Snow shower' : 'Snow shower',
    'Heavy snow shower' : 'Heavy snow shower',

    'Mist' : 'Mist',
    'Smoke' : 'Smoke',
    'Haze' : 'Haze',
    'Sand/dust' : 'Sand/dust',
    'Fog' : 'Fog',
    'Freezing fog' : 'Freezing fog',

    'Clear sky' : 'Clear sky',
    'Clear Sky' : 'Clear Sky',
    'Few clouds' : 'Few clouds',
    'Scattered clouds' : 'Scattered clouds',
    'Broken clouds' : 'Broken clouds',
    'Overcast clouds' : 'Overcast clouds',

    'Unknown Precipitation' : 'Unknown Precipitation',
    // Text trong polutant
    'information_pollutants': 'pm25: Particulate Matter < 2.5 micrometers\n'
                              'pm10: Particulate Matter < 10 micrometers\n'
                              'o3: Ozone\n'
                              'no2: Nitrogen Dioxide\n'
                              'co: Carbon Monoxide ppm\n'
                              'so2: sulfur Dioxide',
    //text button
    'bt_see_more': 'See More Details',
    // Text của đạo
    'language': 'Language',
    'language_unit': 'Language and Unit',
    'Settings': 'Settings',
    'Manage Locations': 'Manage Locations',
    'Add Widgets': 'Add Widgets',
    "Daily Timer Notification": "Daily Timer Notification",
    'More Settings': 'More Settings',
    'SAVED LOCATIONS': 'SAVED LOCATIONS',
    'Use Current Location': 'Use Current Location',
    'Get daily timer notification': 'Get daily timer notification',
    'Select time': 'Select time',
    'Cancel': 'Cancel',
    'OK': 'OK',
    'Alerts': 'Alerts',
    'App Theme': 'App Theme',
    'Auto-Refresh': 'Auto-Refresh',
    'minutes': 'minutes',
    'Additional Settings': 'Additional Settings',
    'Select your': 'Select your interval to automatically refresh notifications',
    'Get hyperlocal': 'Get hyperlocal weather updates for your pinpoint location',
    'Instant Notification': 'Instant Notification',
    'Weather alerts': 'Weather notification from the National Weather Service',
    'Types of Content': 'Types of Content',
    'Weather Highlights': 'Weather Highlights',
    'Get forecasts': 'Get forecasts and alerts in your area',
    'NWS Alerts': 'NWS Alerts',
    'Get weather alerts': 'Get weather alerts from the National Weather Service',
    'Weather News': 'Weather News',
    'Get weather news & videos': 'Get weather news & videos',
    'Location': 'Location',
    'Current Location': 'Current Location',
    'Select Language': 'Select Language',
    'Units': 'Units',
    'Customize': 'Customize',
    'Off': 'Off',
    'Customize Units': 'Customize Units',
    'Temperature': 'Temperature',
    'Wind Units': 'Wind Units',
    'Distance': 'Distance',
    'Select wind': 'Select your preferred win speed unit',
    'Select distance': 'Select your preferred distance unit',
    'Pressure Units': 'Pressure Units',
    'Select pressure': 'Select your preferred pressure unit',
    'Current Selection': 'Current Selection',
    'Select Pressure Unit': 'Select Pressure Unit',
    'Select Theme': 'Select Theme',
    'Light': 'Light',
    'Dark': 'Dark',
    'Weather Update': 'Weather Update',
    'Your weather data is updated!': 'Your weather data is updated!',
    'Notification': 'Notification',

    // Text của chiến
    'Saved Locations': 'Saved Location',
    'SAVED LOCATIONS' : 'SAVED LOCATIONS',
    'Click, hold and move the lever to change the position of your locations.': 'Click, hold and move the lever to change the position of your locations.',
    'Current location': 'Current location',
    'Click to get location': 'Click to get location',
    'Tap on the edit icon to add a label. For e.g., Home, Office...' : 'Tap on the edit icon to add a label. For e.g., Home, Office...',
    'Manage': 'Manage',
    'Search location': 'Search location',
    'Long' : 'Long',
    'Lat': 'Lat',
    "This will remove": "This will remove",
    "from your list of saved locations.": "from your list of saved locations.",
    "Are you sure?": "Are you sure?",
    "Yes": "Yes",
    "No": "No",
    "Item removed successfully": "Item removed successfully",
    "Item not found in history": "Item not found in history",
    "The app does not have access to your location.": "The app does not have access to your location.",
    "Currently": "Currently",
    "Manage Locations": " Manage Locations",
    "Agree": "Agree",
    "Cancel": "Cancel",
    'Location access': 'Location access',
    "Add a label": "Add a label",
    "e.g. Home": "e.g. Home",
    "Home": "Home",
    "School": "School",
    "Hospital": "Hospital",
    "Work": "Work",
    "Gym": "Gym",
    "Park": "Park",
    "Bus": "Bus",
    "Favorite": "Favorite",
    "Other": "Other",
    "SAVE CHANGES": "SAVE CHANGES",
    "The app needs access to your location to provide relevant information. Do you want to allow it?": "The app needs access to your location to provide relevant information. Do you want to allow it?",

  };
  static const Map<String, dynamic> vietnam = {
    'name_app': '1 Weather',
    // Text của duy
    // bottom navigation
    'today': 'HIỆN TẠI',
    'forecast': 'DỰ BÁO',
    'radar': 'RADAR',
    // text ở today screen
    'hourly_forecast': 'THEO GIỜ',
    'current_details': 'HIỆN TẠI',
    'prep': 'Lượng mưa',
    'wind': 'Gió',
    'humi': 'Độ ẩm',
    'visi': 'Tầm nhìn',
    'dew': 'Điểm sương',
    'press': 'Áp suất',
    'daily_forecast': 'THEO NGÀY',
    'air_quality': 'CHẤT LƯỢNG KHÔNG KHÍ',
    'allergy_outlook': 'MỨC ĐỘ DỊ ỨNG',
    'grass': 'phấn hoa cỏ',
    'weed': 'phấn hoa cỏ dại',
    'tree': 'phấn từ cây',
    'sun_moon': 'SUN & MOON',
    //text cua forecast screen
    // text của thứ trong ngày
    // text forecast screen
    'hourly': 'Hàng giờ',
    'daily': 'Hàng Ngày',
    //text trong air_quality_table
    'advice': 'Chất lượng không khí từ 51 đến 100 là không lý tưởng, vì vậy hãy chú ý đến nó',
    // Text  trong current_detail_table
    'feel_like': ' Cảm giác như ',
    // text của weather
    'Thunderstorm with light rain' : 'Dông với mưa nhẹ',
    'Thunderstorm with rain' : 'Dông với mưa',
    'Thunderstorm with heavy rain' : 'Dông với mưa lớn',
    'Thunderstorm with light drizzle' : 'Dông với mưa phùn nhẹ',
    'Thunderstorm with drizzle' : 'Dông với mưa phùn',
    'Thunderstorm with heavy drizzle' : 'Dông với mưa phùn lớn',
    'Thunderstorm with Hail' : 'Dông kèm mưa đá',

    'Light drizzle' : 'Mưa phùn nhẹ',
    'Drizzle' : 'Mưa phùn',
    'Heavy drizzle' : 'Mưa phùn nặng',

    'Light rain' : 'Mưa nhẹ',
    'Moderate rain' : 'Mưa vừa',
    'Heavy rain' : 'Mưa nặng',
    'Freezing rain' : 'Mưa lạnh đóng băng',
    'Light shower rain' : 'Mưa rào nhẹ',
    'Shower rain' : 'Mưa rào',
    'Heavy shower rain' : 'Mưa rào nặng',

    'Light snow' : 'Tuyết nhẹ',
    'Snow' : 'Tuyết',
    'Heavy snow' : 'Tuyết dày',
    'Mix snow/rain' : 'Mưa tuyết',
    'Sleet' : 'Mưa đá tuyết',
    'Heavy sleet' : 'Mưa đá tuyết lớn',
    'Snow shower' : 'Tuyết rào',
    'Heavy snow shower' : 'Tuyết rào dày',

    'Mist' : 'Sương mù',
    'Smoke' : 'Khói',
    'Haze' : 'Mù khô',
    'Sand/dust' : 'Cát/bụi',
    'Fog' : 'Sương mù dày đặc',
    'Freezing fog' : 'Sương mù đóng băng',

    'Clear sky' : 'Trời quang',
    'Clear Sky' : 'Trời quang',
    'Few clouds' : 'Vài đám mây',
    'Scattered clouds' : 'Mây rải rác',
    'Broken clouds' : 'Mây nhiều',
    'Overcast clouds' : 'Mây u ám',

    'Unknown Precipitation' : 'Hiện tượng mưa không xác định',
    // text trong pollutant
    'information_pollutants': 'pm25: Particulate Matter < 2.5 micrometers\n'
                              'pm10: Particulate Matter < 10 micrometers\n'
                              'o3: Ozone\n'
                              'no2: Nitrogen Dioxide\n'
                              'co: Carbon Monoxide ppm\n'
                              'so2: sulfur Dioxide',
    //text button
    'bt_see_more': 'XEM THÊM',
    // Text của đạo
    'language': 'Ngôn Ngữ',
    'language_unit': 'Ngôn Ngữ Và Đơn Vị',
    'Settings': 'Cài Đặt',
    'Manage Locations': 'Quản lý Vị Trí',
    'Add Widgets': 'Thêm Tiện Ích',
    'Daily timer notification': 'Thông Báo Hẹn Giờ Hàng Ngày',
    'More Settings': 'Cài Đặt Khác',
    'SAVED LOCATIONS': 'Vị Trí Đã Lưu',
    'Use Current Location': 'Sử Dụng Vị Trí Hiện Tại',
    'Get daily timer notification': 'Nhận thông báo hẹn giờ hàng ngày',
    'Select time': 'Cài đặt giờ',
    'Cancel': 'Hủy bỏ',
    'OK': 'Chọn',
    'Alerts': 'Cảnh Báo',
    'App Theme': 'Màu Nền',
    'Auto-Refresh': 'Tự động làm mới',
    'minutes': 'phút',
    'Additional Settings': 'Cài Đặt Thêm',
    'Select your': 'Chọn khoảng thời gian của bạn để tự động làm mới thông báo',
    'Get hyperlocal': 'Nhận thông tin cập nhật về thời tiết địa phương cho vị trí chính xác của bạn',
    'Instant Notification': 'Thông báo tức thì',
    'Weather alerts': 'Thông báo thời tiết từ Cơ quan Dịch vụ Thời tiết Quốc gia',
    'Types of Content': 'Các loại nội dung',
    'Weather Highlights': 'Điểm nổi bật thời tiết',
    'Get forecasts': 'Nhận dự báo và cảnh báo trong khu vực của bạn',
    'NWS Alerts': 'Cảnh báo từ NWS',
    'Get weather alerts': 'Nhận cảnh báo thời tiết từ Cơ quan Dịch vụ Thời tiết Quốc gia',
    'Weather News': 'Tin tức thời tiết',
    'Get weather news & videos': 'Nhận tin tức và video về thời tiết',
    'Location': 'Vị trí',
    'Current Location': 'Vị trí hiện tại',
    'Select Language': 'Chọn ngôn ngữ',
    'Units': 'Đơn vị',
    'Customize': 'Tùy chỉnh',
    'Off': 'Tắt',
    'Customize Units': 'Tùy chỉnh đơn vị',
    'Temperature': 'Nhiệt độ',
    'Wind Units': 'Đơn vị gió',
    'Distance': 'Khoảng cách',
    'Select wind': 'Chọn đơn vị tốc độ gió ưa thích',
    'Select distance': 'Chọn đơn vị khoảng cách ưa thích',
    'Pressure Units': 'Đơn vị áp suất',
    'Select pressure': 'Chọn đơn vị áp suất ưa thích',
    'Current Selection': 'Lựa chọn hiện tại',
    'Select Pressure Unit': 'Chọn đơn vị áp suất',
    'Select Theme': 'Chọn chủ đề',
    'Light': 'Sáng',
    'Dark': 'Tối',
    'Weather Update': 'Cập nhật thời tiết',
    'Your weather data is updated!': 'Thời tiết đã được cập nhật',
    'Notification': 'Thông Báo',
    'Daily Timer Notification': 'Thông Báo Hẹn Giờ Hàng Ngày'

    // Text của chiến
    'SAVED LOCATIONS': 'VỊ TRÍ ĐÃ LƯU',
    'Click, hold and move the lever to change the position of your locations.': 'Nhấn, giữ và di chuyển để thay đổi vị trí của các địa điểm của bạn.',
    'Tap on the edit icon to add a label. For e.g., Home, Office...': 'Nhấn vào biểu tượng chỉnh sửa để thêm nhãn. Ví dụ: Nhà, Văn phòng...',
    'Current location': 'Vị trí hiện tại',
    'Click to get location': 'Nhấn để lấy vị trí',
    'Saved Locations': 'Vị trí đã lưu',
    'Manage': 'Quản lý',
    'Search location': 'Tìm kiếm vị trí bất kì',
    'Long' : 'Kinh độ',
    'Lat': 'Vĩ độ',
    "This will remove": "Vị trí",
    "from your list of saved locations.": "sẽ xóa khỏi danh sách các vị trí đã lưu của bạn.",
    "Are you sure?": "Bạn có chắc không?",
    "Yes": "Có",
    "No": "Không",
    "Item removed successfully": "Xóa thành công",
    "Item not found in history": "Không tìm thấy trong lịch sử",
    "The app does not have access to your location.": "Ứng dụng không có quyền truy cập vị trí của bạn.",
    "Currently": "Hiện tại",
    "Manage Locations": "Quản lý vị trí",
    "Agree": "Đồng ý",
    "Cancel": "Hủy",
    'Location access': 'Quyền truy cập vị trí',
    "Add a label": "Thêm nhãn",
    "e.g. Home": "ví dụ: Nhà",
    "School": "Trường",
    "Hospital": "Bệnh viện",
    "Work": "Công ty",
    "Gym": "Gym",
    "Park": "Công viên",
    "Home": "Nhà",
    "Bus": "Xe buýt",
    "Favorite": "Yêu thích",
    "Other": "Khác",
    "SAVE CHANGES": "Lưu thay đổi",
    "The app needs access to your location to provide relevant information. Do you want to allow it?": "Ứng dụng cần truy cập vị trí của bạn để cung cấp thông tin phù hợp. Bạn có muốn cho phép?"
  };
}